# Generated by Django 5.1 on 2024-08-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_users_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cart',
            field=models.JSONField(default='[]'),
        ),
    ]
