# Generated by Django 5.0.6 on 2025-04-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_users_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='total_amount',
            field=models.CharField(db_default='DEFAULT VALUE', max_length=100),
        ),
    ]
