# Generated by Django 5.0.6 on 2025-04-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_users_order_id_users_paid_users_razorpay_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='total_amount',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]   
