# Generated by Django 5.1 on 2025-09-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_users_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='users',
            name='razorpay_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='total_amount',
        ),
    ]
